Updated dark theme for toaster element - icon and dismiss icon visibility
Wai-Technologies/raaghu-react pull request #1078
Opened 2024-11-11 11:46 UTC by rahulp34

## Description

> Updated dark theme for toaster element - icon and dismiss icon visibility

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-11-22 08:13 UTC, hemalatagaikwad requested changes
resolved conflicts
![image](https://github.com/user-attachments/assets/9db611a3-ea87-4806-9edb-4783950d5e45)

2024-12-09 09:46 UTC, poojagurav21 requested changes
Resolve conflicts
![image](https://github.com/user-attachments/assets/a906492d-c215-4332-aee1-b7dc2ad7c45b)

2024-12-12 11:36 UTC, rahulp34 commented
Resolved Conflicts

2024-12-13 05:28 UTC, poojagurav21 requested changes
Alignment issue also check build issues

![image](https://github.com/user-attachments/assets/f023dbb4-b76e-45e5-abc4-9a9b0e368626)

2025-01-07 09:54 UTC, rohit9096 approved these changes
Review and Approved

2025-01-10 10:35 UTC, nknikhilkasar approved these changes
Approved

2025-01-10 11:07 UTC, poojagurav21 approved these changes
Approve

2025-01-10 11:11 UTC, hemalatagaikwad approved these changes
approve

2025-01-10 11:12 UTC, merged