Completed Task 513 : Design System > add new component kanban board
Wai-Technologies/raaghu-react pull request #1113
Opened 2024-11-19 04:33 UTC by DeepashriDatar

## Description

> Kanban board component is added

## ScreenShot 

![image](https://github.com/user-attachments/assets/a9e3ae2d-e8e2-4ccb-909c-ee1fe8d3ff29)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-11-22 12:59 UTC, hemalatagaikwad requested changes
create branch from dev
![image](https://github.com/user-attachments/assets/7617f624-6ecc-4dab-8458-316fe3225ccb)

2024-11-28 08:31 UTC, poojagurav21 requested changes
solve the build issues
![image](https://github.com/user-attachments/assets/c9b4142d-bbc6-415f-9b63-7b1030bc06e9)

2024-12-04 10:42 UTC, poojagurav21 requested changes
Resolve conflicts 
![image](https://github.com/user-attachments/assets/2324f600-573b-4711-b737-b27827499f3e)

2024-12-06 05:02 UTC, poojagurav21 requested changes
Not working as expected 
![image](https://github.com/user-attachments/assets/7037ec96-5dc9-4129-aeaf-d95dcdab0ab9)

2025-02-27 07:13 UTC, closed without merging