Completed Task 1158 : Design system enhancement file uploader component
Wai-Technologies/raaghu-react pull request #1182
Opened 2024-11-27 12:35 UTC by rahulp34

## Description

1] Added multiple file uploader
2] added Show thumbnail true false for single file upload and multiple file upload
3] Added hintposition left and right to multiple file uploader
![image](https://github.com/user-attachments/assets/14af03a4-cc95-4e4f-a30e-456af61460d6)
![image](https://github.com/user-attachments/assets/6d134a80-28dd-48ce-860a-d5bbc8635e9a)
![image](https://github.com/user-attachments/assets/b227f215-b297-4e91-beb1-023862de82d1)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-11-27 13:49 UTC, hemalatagaikwad requested changes
duplicate files uploaded
![image](https://github.com/user-attachments/assets/5d43cc69-c1a8-46db-a944-7e18d1ef665a)

2024-12-02 09:04 UTC, poojagurav21 requested changes
Resolve build issues
![image](https://github.com/user-attachments/assets/6ea99192-8884-4ffc-aae3-d49efda2ad16)

2024-12-02 09:23 UTC, poojagurav21 approved these changes

2024-12-02 09:30 UTC, hemalatagaikwad approved these changes
review and approve

2024-12-02 09:30 UTC, merged