Resolved Bug 1258 : Design System > Element > Toaster > Position issue
Wai-Technologies/raaghu-react pull request #1259
Opened 2024-12-12 10:27 UTC by VenuKG

## Description

> Resolved issue in elements :
1. Changes for toast - add property position dropdown

-  **Toast**

> Make the changes to rds-toast.tsx, placement.ts and rds-toast.stories.tsx

## Screenshots : 
![image](https://github.com/user-attachments/assets/2e54defe-ffd4-4f85-b6ed-484b6e83c1ef)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-12-12 11:08 UTC, poojagurav21 commented on raaghu-react-themes/src/styles/toast.scss
remove commented code if not needed

2024-12-12 11:08 UTC, poojagurav21 requested changes
remove commented code if not needed

2024-12-12 11:54 UTC, VenuKG commented on raaghu-react-themes/src/styles/toast.scss
commented code removed

2024-12-13 04:33 UTC, poojagurav21 approved these changes

2024-12-13 04:33 UTC, merged