Resolved Bug 1251 : Design System > Component > Chatbot > Overlapping issue and pop-up closing issue
Wai-Technologies/raaghu-react pull request #1262
Opened 2024-12-12 11:41 UTC by VenuKG

## Description

> Resolved issue in component :
1. Changes for chatbot - Placeholder and icon are overlapped in emoji picker
2. The pop-up is not closing without adding any emoji.

-  **Chatbot**

> Make the changes to rds-comp-chat.tsx and rds-comp-chat.scss

## Screenshots : 
![image](https://github.com/user-attachments/assets/27e912a0-ab6f-4f20-8b88-72d8b25bf7bc)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-12-13 06:20 UTC, poojagurav21 requested changes
Check alignment 
![image](https://github.com/user-attachments/assets/4ff896f1-1daa-406d-9794-75701cf622f7)

2025-01-10 05:24 UTC, VenuKG commented
![image](https://github.com/user-attachments/assets/3c24dd87-ff82-49e7-8b09-7fde9768e843)
Design implementing after discuss with UI team(Shalvi)

2025-01-10 07:20 UTC, nknikhilkasar commented
fixed the alignment
![1262](https://github.com/user-attachments/assets/ad3c4072-cada-4f31-ada0-648935ff0070)

2025-01-10 09:55 UTC, VenuKG commented
@nknikhilkasar Alignment issue resolved--code pushed
![image](https://github.com/user-attachments/assets/52e11d0c-9afe-4489-bc09-a4bfbd974acb)

2025-01-10 10:01 UTC, nknikhilkasar approved these changes
Approved

2025-01-10 10:58 UTC, poojagurav21 approved these changes

2025-01-10 11:02 UTC, poojagurav21 approved these changes
Approve

2025-01-10 11:03 UTC, merged