Resolved Bug 1148: Components Webhook Subscription Default Text alignment issue
Wai-Technologies/raaghu-react pull request #1299
Opened 2024-12-17 06:30 UTC by Sachin-Ghorpade

## Description
> Resolve the issues on Components Webhook Subscription Default Text alignment: 
-  **Resolved Text alignment issue**
-  **Resolved Small view Popup is hide**

## Screenshots :
![image](https://github.com/user-attachments/assets/164d1b29-f6de-4dd9-b250-d55efbe96ceb)
![image](https://github.com/user-attachments/assets/7abb5165-4840-45aa-a73c-2c9b20a14bba)

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2025-01-06 09:19 UTC, WAi-Aditya requested changes

2025-01-06 09:19 UTC, WAi-Aditya commented on raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
> -                        <div className="col-12 col-md-2 mb-3 mt-1 d-flex justify-content-center justify-content-md-end">
We should not change this code, 
Alignment is getting disturb because of the same.

![image](https://github.com/user-attachments/assets/3219ea53-0783-4d75-a0cd-b7882e205641)

2025-01-07 06:54 UTC, Sachin-Ghorpade commented on raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
> -                        <div className="col-12 col-md-2 mb-3 mt-1 d-flex justify-content-center justify-content-md-end">
This Issue is resolved.

2025-01-07 08:40 UTC, WAi-Aditya approved these changes

2025-01-14 07:22 UTC, merged