Resolved bug 1129 : Design System > Components > Identity Client Basic > Default > Required Consent alignment issue.
Wai-Technologies/raaghu-react pull request #1314
Opened 2024-12-23 05:30 UTC by nitinsonawane123

## Description
> Resolve the issues on Components: 
1. Resolved issue on Components Identity Client Basics - Description & Required Consent alignment issue.

## Screenshots :
 
![image](https://github.com/user-attachments/assets/2cf11e41-845a-4091-b711-6423290a99ad)

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-12-27 09:11 UTC, poojagurav21 requested changes
Alignment issue
![image](https://github.com/user-attachments/assets/124d6d81-2647-4599-afbc-31f6b325eebd)

2024-12-27 09:32 UTC, nitinsonawane123 commented
Resolved alignment issue.
![image](https://github.com/user-attachments/assets/ec5c40eb-7a19-4583-aeb0-88218dc95f66)

2025-01-06 05:06 UTC, WAi-Aditya approved these changes

2025-01-20 10:47 UTC, poojagurav21 approved these changes

2025-01-20 10:47 UTC, merged