Resolved bug 1149 : Design System > Application Shells > Default > UI issue.
Wai-Technologies/raaghu-react pull request #1320
Opened 2024-12-24 08:38 UTC by nitinsonawane123

## Description
> Resolve the issues on Application Shells: 
1. Resolved issue on Application Shells - Default - UI issue.

## Screenshots :
 
![image](https://github.com/user-attachments/assets/5abe9748-2a43-49a5-af34-af0e808416db)
![image](https://github.com/user-attachments/assets/e1f4128b-1ae2-4a29-bde4-dae972c80b36)
![image](https://github.com/user-attachments/assets/3a31b737-bb9c-4394-8b83-d2147d58a3d4)

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2025-01-06 05:50 UTC, WAi-Aditya commented
Alignment issue
![image](https://github.com/user-attachments/assets/5f04d3c7-0329-43b9-96d3-9f551bcc187a)

2025-01-06 05:50 UTC, WAi-Aditya requested changes
Alignment issue

![image](https://github.com/user-attachments/assets/695e07e6-54fb-4752-b16f-a51aa893fed0)

2025-01-20 11:07 UTC, nitinsonawane123 commented
It is working fine.
![image](https://github.com/user-attachments/assets/55e5cb2d-4f63-46c5-9fb0-86b745ce78f8)

2025-01-21 11:08 UTC, WAi-Aditya approved these changes

2025-01-21 11:20 UTC, merged