Resolved bug 1241 : Design System > Components > Add validations.
Wai-Technologies/raaghu-react pull request #1323
Opened 2024-12-26 10:01 UTC by nitinsonawane123

## Description
> Resolve the issues on Components: 
1. Resolved issue on Components Form Email: email validation is required.
2. Register member -> need validation of password.
3. Set Password -> use existing validation of password.
4. input-> passwords - validation (password)
5. Tenant Setting -> use existing validation of password.

## Screenshots :
 
![image](https://github.com/user-attachments/assets/164078bf-507a-4e33-b16d-2d08addf9f61)
![image](https://github.com/user-attachments/assets/1ef7383f-588c-4c07-ac4b-118fb660ff3a)
![image](https://github.com/user-attachments/assets/08493277-3b11-4e0a-a0a7-7d68edbcbeb8)
![image](https://github.com/user-attachments/assets/fc1d5de7-81f9-459e-aa07-b86a134a395f)
![image](https://github.com/user-attachments/assets/113c56cb-0ba3-4e4e-ac09-d256500814a9)

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2025-01-06 06:43 UTC, WAi-Aditya requested changes
Register Member - Password validation not working as expected,
Even if we type more than 8 words of alphanumeric characters, Password validation message does not get disappear.

![image](https://github.com/user-attachments/assets/2ea2df91-2049-4366-aee8-45c857993130)

2025-01-20 05:47 UTC, nitinsonawane123 commented
It is working fine. 
![image](https://github.com/user-attachments/assets/e2320f57-bc5b-47e5-b482-20d461faa54b)

2025-01-21 12:52 UTC, WAi-Aditya requested changes
![image](https://github.com/user-attachments/assets/6f1cbd06-1a0a-4d0a-ae5c-ef87d7b70a4c)

Please check UI margin issue.

2025-01-22 04:43 UTC, nitinsonawane123 commented
Resolved margin issue.
![image](https://github.com/user-attachments/assets/6a9e36dd-7e58-4c98-9aab-7af26247e067)

2025-01-24 11:21 UTC, poojagurav21 approved these changes

2025-01-27 12:27 UTC, WAi-Aditya approved these changes

2025-01-27 12:30 UTC, merged