Completed task 1232 : Design System > Application > Enhancement in Comment component, File Uploader component, Accordion position and Nav tab badges
Wai-Technologies/raaghu-react pull request #1326
Opened 2024-12-27 05:07 UTC by nitinsonawane123

## Description
> Resolve the issues on Application: 
1. Comment component -- Add, Delete Props not available. Delete icon misplaced : Chat Component.
2.  Nav Tab
 
 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2025-01-06 06:26 UTC, WAi-Aditya requested changes

2025-01-06 06:26 UTC, WAi-Aditya commented on raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
> +      // Get the id of the comment to be deleted
Try with below code for better readability and maintainability

const handleDeleteComment = (index: number) => {
  if (!allowDelete) return;

  // Get the comment to be deleted
  const commentToDelete = commentList[index];
  const commentId = commentToDelete?.commentId; 

  if (!commentId) return; 

  // Update the comments list
  setCommentList((prevList) => prevList.filter((_, i) => i !== index));

  props.handleDeleteComment?.(commentId);
};

2025-01-20 05:06 UTC, nitinsonawane123 commented
done

2025-01-21 12:34 UTC, WAi-Aditya approved these changes

2025-01-21 12:40 UTC, merged