Bug 470 and 481: Elements >Notification> Selecting dark theme button text is not display and Storybook > Elements >Card Detail >Selecting small mobile view radio button is stick on card text.
Wai-Technologies/raaghu-react pull request #490
Opened 2024-07-10 11:45 UTC by pravinwaghmare23

## Description
> Make the changes to rds-widget-portal.css, rds-size.css, rds-notification.css, rds-card-detail.tsx, rds-avatar.css
> Resolved Elements>Notification> Default > Selecting dark theme button text is not display.
> Resolved Elements>Size >With Description> Selecting dark theme card text is not display.
> Resolved Elements>Widget Portal > Default >Selecting dark theme button text is not display.
> Resolved Elements>Card Details > Card Details > Selecting small mobile view radio button is stick on card text.
> Resolved Elements>Avatar >With Initial >Selecting dark theme Initial latter is not display.
> Resloved Elements>Avatar >With Label>Selecting dark theme label is not display proper.

## Screenshot :-
> Elements>Notification> Default 
![image](https://github.com/Wai-Technologies/raaghu-react/assets/113504664/eaf9891f-7d60-4539-8951-f9d64d795c21)

> Elements> Size >With Description
![image](https://github.com/Wai-Technologies/raaghu-react/assets/113504664/37bf6574-1f7a-4aeb-9079-43f1bdb4c536)

> Elements> Widget Portal > Default 
![image](https://github.com/Wai-Technologies/raaghu-react/assets/113504664/818db533-1671-4e23-a671-28143bf30159)

> Elements> Card Details > Card Details 
![image](https://github.com/Wai-Technologies/raaghu-react/assets/113504664/d47bf4fd-629d-4a76-a492-ae0202db32fd)

> Elements>Avatar >With Initial 
![image](https://github.com/Wai-Technologies/raaghu-react/assets/113504664/c0af8060-df89-429e-89e9-0b57697473f1)

> Elements>Avatar >With Label
![image](https://github.com/Wai-Technologies/raaghu-react/assets/113504664/d3d2bd8f-bb36-4b43-80e2-2cd631a8d6c0)

 

 

## Checklist:
 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New

2024-07-12 06:51 UTC, suraj-khupse requested changes

2024-07-12 06:51 UTC, suraj-khupse commented on raaghu-elements/src/rds-card-detail/rds-card-detail.tsx
> +                                            <div className="ms-1 text-nowrap">
no need no wrap

2024-07-12 09:24 UTC, pravinwaghmare23 commented on raaghu-elements/src/rds-card-detail/rds-card-detail.tsx
> +                                            <div className="ms-1 text-nowrap">
Resolved Comments

2024-07-15 07:44 UTC, Ketan-Khalate approved these changes

2024-07-15 07:51 UTC, Ketan-Khalate approved these changes

2024-07-15 08:37 UTC, suraj-khupse approved these changes

2024-07-15 08:38 UTC, merged