Bug 467, 482, 485 : Resolved Issues on Counter, Collapse, Button & Card Element Issues
Wai-Technologies/raaghu-react pull request #493
Opened 2024-07-10 14:11 UTC by AkshayPotphode

## Description
> Resolve the issues on Element Radio button unable to select: 
-  **Counter**
-  **Collapse**
-  **Button**
-  **Card**

> Make the changes to rds-button.css, rds-card.stories.tsx, rds-card.tsx, rds-collapse.tsx & rds-counter.css file.
> Resolve issue on light color varient outline is not visible & in dark theme with dark color varient +,- icons ia not visible in counter element.
> Resolved spacing issue on Toggle element.
> Resolved issue on selecting dark theme with color varient light button text is not visible on all stories in button element.
> Resolved issue on selecting dark theme with light color varient button text is not visible on all stories & Avatar and with centered avatar, Avatar profile is not visible.

## Screenshots :
 
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155605401/d482bd5e-5b17-4347-b1c7-390ccbe60946)

![image](https://github.com/Wai-Technologies/raaghu-react/assets/155605401/7403f24a-2692-4fa3-a963-e5637b72cd50)

![image](https://github.com/Wai-Technologies/raaghu-react/assets/155605401/b679771e-b3c1-49c8-a5dc-db5e23305799)

![image](https://github.com/Wai-Technologies/raaghu-react/assets/155605401/492237b9-7a2f-4a37-9a31-f4b22e60279c)

![image](https://github.com/Wai-Technologies/raaghu-react/assets/155605401/68ec8f93-87a9-45f1-a84a-9b4a7ec7fe26)

![image](https://github.com/Wai-Technologies/raaghu-react/assets/155605401/683b7861-53ba-496b-9f3e-27324d8ba533)

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-07-12 06:52 UTC, suraj-khupse requested changes

2024-07-12 06:52 UTC, suraj-khupse commented on raaghu-elements/src/rds-button/rds-button.css
> +.theme-dark .btn-light {
please do not used hard code color variable

2024-07-12 06:52 UTC, suraj-khupse commented on raaghu-elements/src/rds-collapse/rds-collapse.tsx
> +                    className="btn btn-primary btn-sm ms-1"
Check with raaghu application as well , add screenshot

2024-07-12 06:52 UTC, suraj-khupse commented on raaghu-elements/src/rds-counter/rds-counter.css
> +}
remove css from element

2024-07-15 05:07 UTC, AkshayPotphode commented
Done

2024-07-15 08:41 UTC, AkshayPotphode commented on raaghu-elements/src/rds-button/rds-button.css
> +.theme-dark .btn-light {
No change

2024-07-15 08:42 UTC, AkshayPotphode commented on raaghu-elements/src/rds-counter/rds-counter.css
> +}
Added css in counter.css

2024-07-15 08:45 UTC, AkshayPotphode commented on raaghu-elements/src/rds-collapse/rds-collapse.tsx
> +                    className="btn btn-primary btn-sm ms-1"
Not required

2024-07-15 09:20 UTC, suraj-khupse approved these changes

2024-07-15 09:47 UTC, suraj-khupse approved these changes

2024-07-15 09:47 UTC, merged