#655 billing address address label issue resolved
Wai-Technologies/raaghu-react pull request #739
Opened 2024-09-27 10:17 UTC by suchithravipin1991

#655 billing address address label issue resolved

Address is visible instead of Enter Address
## Description

Label Modified
Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

Navigate to 'Storybook >Component > Billing Address >Default'
Check label on address => Enter Address

![addess](https://github.com/user-attachments/assets/aca2a7d9-7f6b-4c8b-9119-6709bc535626)

2024-10-01 04:20 UTC, hemalatagaikwad commented
@suchithravipin1991  please add checklist in conversation

2024-10-01 04:20 UTC, hemalatagaikwad requested changes

2024-10-01 04:20 UTC, hemalatagaikwad commented on raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
> +                                placeholder=" Enter Address"
remove blank space

2024-10-03 06:53 UTC, hemalatagaikwad approved these changes
ok

2024-10-07 09:22 UTC, omkarchoudhari approved these changes

2024-10-07 11:02 UTC, hemalatagaikwad approved these changes
ok

2024-10-07 11:04 UTC, hemalatagaikwad approved these changes
ok

2024-10-07 12:52 UTC, hemalatagaikwad commented
close this pr as new pr created against this task https://github.com/Wai-Technologies/raaghu-react/pull/799

2024-10-07 12:52 UTC, closed without merging